cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: <access-key>
      secret-key: <secret-key>
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/961911238890/sqs-queue
server:
  port: 8083
