cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA575TAWDVE3HMDDX7
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/961911238890/sqs-queue
server:
  port: 8083
